api/urls.py
from rest_framework import routers
from django.urls import path
from maps import api as map_views
from campaigns import api as campaign_views

app_name = 'api'


router = routers.SimpleRouter()
router.register(r'maps', map_views.MapViewSet)
router.register(r'campaigns', campaign_views.CampaignViewSet)

urlpatterns = router.urls

campaigns/urls.py
from django.urls import path

from campaigns import views

urlpatterns = [
    path('new/', views.CampaignCreateView.as_view(), name='new'),
    path('<slug:slug>/', views.CampaignHomeView.as_view(), name='campaign_home'),
    path('', views.CampaignLandingPageView.as_view(), name='campaign_list'),
]

dndweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


from dndweb import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('campaigns/', include(('campaigns.urls', 'campaigns'), namespace='campaigns')),
    path('maps/', include(('maps.urls', 'maps'), namespace='maps')),
    path('', views.LandingRedirectView.as_view(), name='landing_page'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaigns/models.py
import uuid
from django.db import models


def campaign_banner_upload_to(instance, filename):
    file_type = filename.split('.')[-1]
    return '{0}/{1}/banner.{2}'.format('campaign', instance.uuid, file_type)


class Campaign(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)  # external ID
    name = models.CharField(max_length=255)
    banner = models.ImageField(
        blank=True,
        null=True,
        upload_to=campaign_banner_upload_to)

    dungeon_master = models.ForeignKey('users.User', related_name='campaign_dungeon_master', on_delete=models.CASCADE)
    players = models.ManyToManyField('users.User', related_name='campaign_players')

    created_by = models.ForeignKey('users.User', related_name='campaign_created_by', on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

campaigns/forms.py
from django import forms

from campaigns.models import Campaign


class NewCampaignForm(forms.ModelForm):
    class Meta:
        model = Campaign
        fields = (
            'name',
            'banner'
        )

campaigns/views.py
import json

from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from campaigns.models import Campaign
from campaigns.forms import NewCampaignForm

from maps.forms import NewMapForm
from maps.serializers import MapNoLayersSerializer


class CampaignLandingPageView(LoginRequiredMixin, ListView):
    template_name = "campaigns/home.html"
    model = Campaign

    def get_context_data(self, *args, **kwargs):
        return super().get_context_data(*args, **kwargs)


class CampaignCreateView(LoginRequiredMixin, FormView):
    template_name = "campaigns/edit.html"
    form_class = NewCampaignForm
    success_url = ''

    def get_success_url(self):
        return '/campaigns/{0}/'.format(self.object.uuid)

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.banner = self.request.FILES['banner']
        self.object.dungeon_master = self.request.user
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)


class CampaignHomeView(LoginRequiredMixin, DetailView):
    template_name = "campaigns/campaign_home.html"
    model = Campaign
    slug_field = 'uuid'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['maps'] = json.dumps(MapNoLayersSerializer(self.object.worldmap_set.order_by('order'), many=True).data)
        context['map_form'] = NewMapForm()
        return context

campaigns/templates/campaigns/campaign_home.html
{% extends "base.html" %}

{% load static %}
{% load django_bootstrap5 %}

{% block additional_nav_links %}
  <li class="nav-item">
    <a class="nav-link" aria-current="page" href="/campaigns/">Campaigns</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="/campaigns/{{ object.uuid }}/">{{ object.name }}</a>
  </li>
{% endblock %}

{% block main_content %}
<div class="container">
  <h2> {{ object.name }} </h2>
  
  <div class="row">
    <div class="col-6">
      <img src="/media/{{ object.banner }}" class="img-fluid" alt="...">
    </div>
    <div class="col-6">
      <ul class="list-group">
        <li class="list-group-item"> DM: {{ object.dungeon_master.username }}</li>
      </ul>
      <ul class="list-group">
      	{% for player in object.players.all %}
      	<li class="list-group-item" >{{ player.username }}</li>
      	{% endfor %}
      </ul>
    </div>
  </div>
  <button class="btn btn-primary float-end" id="newMapButton" data-bs-toggle="modal" data-bs-target="#newMapModal">New Map</button>
  <h3 class="mt-2">My Maps</h3>
  <div class="row">
  	<div class="col" >

  		<ul class="list-group" id="map_container">
        <li class="list-group-item" rv-each-item="items" rv-on-dragstart="drag_start" rv-on-dragend="drag_end" rv-on-dragenter="drag_enter" rv-on-dragleave="drag_leave" rv-on-drop="drag_drop" rv-on-dragdrop="dragdrop" rv-on-dragover="drag_over" draggable="true" rv-on-click="on_click">
          {item.name}


        </li>  
      </ul>
  	</div>
  </div>
</div>

<div class="modal" tabindex="-1" id="newMapModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Map</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form id="newMapForm" action="" method="POST">
        <div class="modal-body">
          {% bootstrap_form map_form %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" id="newMapSaveButton">Save changes</button>
        </div>
      </form>
    </div>

  </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static "tinybind/tinybind.min.js" %}"></script>
<script>
(function() {
  var dragSrcIndex = null;
  var mapModel = {
    items: {{ maps|safe }},
    maps: {},
    drag_start(event, model) {
      model.$parent.is_dragging = true;
      this.style.opacity = '0.4';
      dragSrcIndex = model.$index;
    },
    drag_end(event, model) {
      this.style.opacity = '1';

      var children = document.getElementById('map_container').children;
      for(var i=0; i<children.length; i++){
          var child = children[i];
          child.classList.remove('over');
      }
      this.is_dragging = false;
    },
    drag_enter(event, model) {
      event.preventDefault();
      this.classList.add('over');
    },
    drag_leave(event, model) {
      event.preventDefault();
      this.classList.remove('over');
    },
    drag_over(event, model) {
      event.preventDefault();
      this.classList.remove('over');
    },
    drag_drop(event, model) {
      // event.stopPropagation();
      let finalSrcIndex = dragSrcIndex;
      let finalDestIndex = model.$index;
      if (dragSrcIndex !== model.$index) {
          if(model.$index == 0) {
            finalSrcIndex = dragSrcIndex;
            finalDestIndex = 0;
          }
        _dragged_item = model.$parent.items.splice(finalSrcIndex, 1);
        model.$parent.items.splice(finalDestIndex, 0, _dragged_item[0]);
        
      }

      // update order
      for(var i = 0; i < model.$parent.items.length; i++) {
        model.$parent.items[i].order = i;
      }
      model.$parent.is_dragging = false;
      model.$parent.update_order()
      return false;
    },
    on_click(event, model) {
      window.location.assign('/maps/'+model.item.uuid+'/');
    },
    update_order() {
      var payload = {
        'order': {}
      }
      for(var i = 0; i < this.items.length; i++) {
        payload['order'][this.items[i].uuid] = this.items[i].order;
      }
      fetch("/api/campaigns/{{ object.uuid }}/update_order/", {
            method: "POST",
            body: JSON.stringify(payload),
            headers: {
              'X-CSRFToken': getCookie('csrftoken'),
              'Content-Type': 'application/json'
            }
        }
      ).then(function(res){ return res.json(); })
       .then(function(jsonResponse){});
    }
  }
  window.mapBinding = tinybind.bind(document.getElementById('map_container'), mapModel);

  document.getElementById('newMapSaveButton').addEventListener('click', (e) => {
    var form = document.getElementById('newMapForm');
    if (form.checkValidity() == false) {
        return false;
    }
    e.preventDefault();
    let formdata = new FormData(form);
    var payload = serialize(formdata);
    payload['campaign'] = '{{ campaign.uuid }}'; 
    fetch("/api/maps/",
      {
          method: "POST",
          body: JSON.stringify(payload),
          headers: {
            'X-CSRFToken': getCookie('csrftoken'),
            'Content-Type': 'application/json'
          }
      }
    ).then(function(res){ return res.json(); })
     .then(function(jsonResponse){location.reload()});
  });
})();
</script>
{% endblock %}

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModalLive">
    Launch demo modal
  </button>

campaigns/templates/campaigns/edit.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block main_content %}
<div class="container">
  <h2> Edit Campaign </h2>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      <div class="col">
        {% bootstrap_form form %}
      </div>
    </div>
    <div class="row">
      <div class="col">
        <button class="btn btn-primary">Save</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

campaigns/templates/campaigns/home.html
{% extends "base.html" %}

{% block main_content %}
<div class="container">
  <h2> My Campaigns </h2>
  <div class="row">
  {% for campaign in object_list %}
    <div class="col-2">
      <div class="card">
        <div class="card-header">
          {{ campaign.name }}
        </div>
        {% if campaign.banner %}
        <img src="/media/{{ campaign.banner }}" width="100%" />
        {% endif %}
        <div class="card-body">
          Next Game: 08-28-85 04:30PM CST
        </div>
        <div class="card-footer">
          <a href="{% url 'campaigns:campaign_home' campaign.uuid %}" class="btn btn-primary">Launch</a>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>
{% endblock %}